trigger:
- development

pool:
  name: pusula-akademi-team2-agent

name: $(Date:yyyyMMdd).$(Rev:r)


steps:

- task: Bash@3
  displayName: 'Docker Image Tag Formatını Belirle'
  inputs:
    targetType: 'inline'
    script: |
      # Tag formatını hazırlıyoruz
      TAG=$(echo "$(Build.SourceVersion:0:7)-$(Build.QueuedTime:yyyyMMdd-HHmm)")
      
      # Docker build için değişkeni kaydediyoruz
      echo "##vso[task.setvariable variable=DOCKER_TAG]$TAG"
- task: Docker@2
  displayName: 'Docker Image Build'
  inputs:
    repository: 'Blazorapp'
    command: 'build'
    Dockerfile: '**/Dockerfile-BlazorApp'
    tags: $(imageTag)
    buildArguments: '--memory=4g --cpu-shares=1024'

- task: Bash@3
  displayName: 'Image’i Tagle'
  inputs:
    targetType: 'inline'
    script: |
      docker tag blazorapp:$(imageTag) registry.gitlab.com/medplus1/medplusproject:$(imageTag)

- task: Docker@2
  displayName: 'Docker Image Push'
  inputs:
    containerRegistry: 'GitLab'
    repository: 'medplus1/medplusproject'
    command: 'push'
    tags: '$(imageTag)'
